"""Console limits from ConsoleSpecs.md."""

SCREEN_WIDTH = 264
SCREEN_HEIGHT = 198

MAX_COLORS = 64
SPRITE_BLOCK = 4
TILE_BLOCK = 8
TILE_LAYERS = 4
BACKGROUND_LAYERS = 4
GUI_LAYERS = 4

DEFAULT_FPS = 60
