"""Generates each object's <script>_auto.py sidecar file.

Part of the two-file object-script scheme: the developer's own `script.py`
imports named constants (animation names, collider names, origin, ...) from
`<script>_auto.py`, which TortuStudio fully regenerates every time the owning
`.tortuobject` is saved. Never hand-edit a generated file — the next save
overwrites it.

Generated sidecars live under `scripts/_generated/`, mirroring the script's
location relative to the project's `scripts/` directory, so hand-written
scripts and generated files never share a folder. A script imports its
sidecar as an absolute import, e.g. `from scripts._generated import
mechaturtle_player_auto as auto` — this works whether the importing script
itself was loaded as a package member or exec'd standalone (see
tortuengine/instance_scripts.py), since it doesn't rely on `__package__`.

Naming convention: `ANIM_<NAME>` per animation, `DEFAULT_ANIMATION`,
`COLLIDER_<NAME>` per collider, `SOLID`, `ORIGIN`. Constant values are always
the runtime lookup key (animation/collider name) as authored in TortuStudio,
never resolved pixel data — including any typos, so renaming an animation in
the object editor is the only way to change the generated constant.

The same scheme applies at the scene level: a scene's own `script` gets a
`<script>_auto.py` sidecar with `OBJ_<ID>` per placed object instance that has
an id, and `LINKS_<ID>` per instance whose `links` list is non-empty — because
links are per-placed-instance scene data, not part of the shared object
prefab, they can only be generated here rather than in an object's own
`_auto.py` (see tortuengine/scene.py's `SceneObject.links`).
"""

from __future__ import annotations

import re
import textwrap
from pathlib import Path

from tortuengine.object import TortuObject
from tortuengine.scene import Scene

_FOOTER = "# ==== END AUTOGENERATED ====\n"
_GENERATED_DIRNAME = "_generated"


def _sanitize(name: str) -> str:
    ident = re.sub(r"[^0-9a-zA-Z]+", "_", name.strip()).strip("_").upper()
    if not ident:
        ident = "UNNAMED"
    if ident[0].isdigit():
        ident = f"_{ident}"
    return ident


def auto_script_path(project_root: Path, script: str) -> Path | None:
    """Path to the `_auto.py` sidecar for a `script` field, or None if unset.

    Lives under `scripts/_generated/`, mirroring the script's location
    relative to `scripts/` (falling back to a flat filename if the script
    isn't under `scripts/` at all).
    """
    if not script:
        return None
    script_path = (project_root / script).resolve()
    scripts_dir = (project_root / "scripts").resolve()
    try:
        rel = script_path.relative_to(scripts_dir)
    except ValueError:
        rel = Path(script_path.name)
    return scripts_dir / _GENERATED_DIRNAME / rel.parent / f"{rel.stem}_auto.py"


def _ensure_generated_packages(generated_dir: Path, scripts_dir: Path) -> None:
    """Create empty `__init__.py` markers from `scripts/_generated` down to *generated_dir*."""
    current = scripts_dir / _GENERATED_DIRNAME
    current.mkdir(parents=True, exist_ok=True)
    (current / "__init__.py").touch(exist_ok=True)
    rel = generated_dir.relative_to(current)
    for part in rel.parts:
        current = current / part
        current.mkdir(parents=True, exist_ok=True)
        (current / "__init__.py").touch(exist_ok=True)


def generate_object_auto_script(obj: TortuObject) -> str:
    anim_consts = [f"ANIM_{_sanitize(anim.name)}" for anim in obj.animations]

    default_animation = obj.default_animation
    if not default_animation or not any(a.name == default_animation for a in obj.animations):
        default_animation = obj.animations[0].name if obj.animations else ""
    default_const = None
    for anim, const in zip(obj.animations, anim_consts):
        if anim.name == default_animation:
            default_const = const
            break

    collider_consts = [f"COLLIDER_{_sanitize(c.name)}" for c in obj.colliders]

    quick_ref = anim_consts + (["DEFAULT_ANIMATION"] if default_const else [])
    quick_ref += collider_consts + ["SOLID", "ORIGIN"]

    body_lines: list[str] = []
    for anim, const in zip(obj.animations, anim_consts):
        body_lines.append(f'{const} = "{anim.name}"')
    if default_const:
        body_lines.append(f"DEFAULT_ANIMATION = {default_const}")

    if collider_consts:
        body_lines.append("")
        for col, const in zip(obj.colliders, collider_consts):
            body_lines.append(f'{const} = "{col.name}"')

    body_lines.append("")
    body_lines.append(f"SOLID = {obj.solid!r}")
    body_lines.append(f"ORIGIN = ({obj.origin.x}, {obj.origin.y})")

    header = (
        f"# ==== AUTOGENERATED BY TORTUSTUDIO — regenerated every time {obj.name}.tortuobject\n"
        "# is saved in TortuStudio. If you modify this file it will be overwritten. ====\n"
    )
    ref_comment = textwrap.fill(
        "Quick reference: " + ", ".join(quick_ref),
        width=78,
        initial_indent="# ",
        subsequent_indent="# ",
    )
    return header + ref_comment + "\n\n" + "\n".join(body_lines) + "\n" + _FOOTER


def write_object_auto_script(obj: TortuObject, project_root: Path) -> Path | None:
    """Regenerate the object's `_auto.py` sidecar; no-op if it has no script."""
    path = auto_script_path(project_root, obj.script)
    if path is None:
        return None
    _ensure_generated_packages(path.parent, (project_root / "scripts").resolve())
    path.write_text(generate_object_auto_script(obj), encoding="utf-8")
    return path


def generate_scene_auto_script(scene: Scene) -> str:
    obj_consts: dict[str, str] = {}
    for inst in scene.objects:
        if inst.id and inst.id not in obj_consts:
            obj_consts[inst.id] = f"OBJ_{_sanitize(inst.id)}"

    obj_lines = [f'{const} = "{inst_id}"' for inst_id, const in obj_consts.items()]

    links_lines: list[str] = []
    links_consts: list[str] = []
    for inst in scene.objects:
        if not inst.id or not inst.links:
            continue
        const = f"LINKS_{_sanitize(inst.id)}"
        links_consts.append(const)
        refs = [obj_consts.get(link_id, repr(link_id)) for link_id in inst.links]
        tuple_body = f"({refs[0]},)" if len(refs) == 1 else "(" + ", ".join(refs) + ")"
        links_lines.append(f"{const} = {tuple_body}")

    quick_ref = list(obj_consts.values()) + links_consts

    header = (
        "# ==== AUTOGENERATED BY TORTUSTUDIO — regenerated every time this scene\n"
        "# is saved in TortuStudio. If you modify this file it will be overwritten. ====\n"
    )
    if quick_ref:
        ref_comment = textwrap.fill(
            "Quick reference: " + ", ".join(quick_ref),
            width=78,
            initial_indent="# ",
            subsequent_indent="# ",
        )
    else:
        ref_comment = "# (no placed object instance in this scene has an id yet)"

    body_lines = list(obj_lines)
    if links_lines:
        if body_lines:
            body_lines.append("")
        body_lines.extend(links_lines)
    if not body_lines:
        body_lines = ["# Assign ids to placed objects in the scene editor to see them here."]

    return header + ref_comment + "\n\n" + "\n".join(body_lines) + "\n" + _FOOTER


def write_scene_auto_script(scene: Scene, project_root: Path) -> Path | None:
    """Regenerate the scene's `_auto.py` sidecar; no-op if it has no script."""
    path = auto_script_path(project_root, scene.script)
    if path is None:
        return None
    _ensure_generated_packages(path.parent, (project_root / "scripts").resolve())
    path.write_text(generate_scene_auto_script(scene), encoding="utf-8")
    return path
