# ==== AUTOGENERATED BY TORTUSTUDIO — regenerated every time audio channels
# or file assignments are saved in the Sound Editor. If you modify this file
# it will be overwritten. ====
# Quick reference: CHANNEL_MUSIC, CHANNEL_GAME_SFX, CHANNEL_UI_SFX,
# AUDIO_CHANNELS

CHANNEL_MUSIC = "music"
CHANNEL_GAME_SFX = "game_sfx"
CHANNEL_UI_SFX = "ui_sfx"

# Project-relative audio file path -> its assigned channel constant above.
AUDIO_CHANNELS = {
    'assets/audio/DialogueNext.ogg': CHANNEL_MUSIC,
    'assets/audio/GameOver (Jingle).ogg': CHANNEL_MUSIC,
    'assets/audio/Hang In There v0_5.ogg': CHANNEL_MUSIC,
    'assets/audio/Hit_shell.ogg': CHANNEL_GAME_SFX,
    'assets/audio/Jingle_checkpoint.ogg': CHANNEL_GAME_SFX,
    'assets/audio/LostLife.ogg': CHANNEL_MUSIC,
    'assets/audio/MenuAccept.ogg': CHANNEL_UI_SFX,
    'assets/audio/Menu_Navigate.ogg': CHANNEL_UI_SFX,
    'assets/audio/Stage Clear Long (Jingle).ogg': CHANNEL_MUSIC,
    'assets/audio/Stage Clear Short (Jingle).ogg': CHANNEL_MUSIC,
    'assets/audio/break_block.ogg': CHANNEL_GAME_SFX,
    'assets/audio/enemydefeat.ogg': CHANNEL_GAME_SFX,
    'assets/audio/every Friday.ogg': CHANNEL_MUSIC,
    'assets/audio/level_complete.ogg': CHANNEL_MUSIC,
    'assets/audio/pause.ogg': CHANNEL_UI_SFX,
    'assets/audio/sfx_attack.ogg': CHANNEL_GAME_SFX,
    'assets/audio/sfx_coin.ogg': CHANNEL_GAME_SFX,
    'assets/audio/sfx_damage.ogg': CHANNEL_GAME_SFX,
    'assets/audio/sfx_defeat.ogg': CHANNEL_GAME_SFX,
    'assets/audio/sfx_jump.ogg': CHANNEL_GAME_SFX,
    'assets/audio/sfx_shell.ogg': CHANNEL_GAME_SFX,
}
# ==== END AUTOGENERATED ====
