# ==== AUTOGENERATED BY TORTUSTUDIO — regenerated every time brick_block.tortuobject
# is saved in TortuStudio. If you modify this file it will be overwritten. ====
# Quick reference: ANIM_DEFAULT, ANIM_BREAK, DEFAULT_ANIMATION, COLLIDER_MAIN,
# SOLID, ORIGIN

ANIM_DEFAULT = "default"
ANIM_BREAK = "break"
DEFAULT_ANIMATION = ANIM_DEFAULT

COLLIDER_MAIN = "main"

SOLID = True
ORIGIN = (8, 8)
# ==== END AUTOGENERATED ====
