# ==== AUTOGENERATED BY TORTUSTUDIO — regenerated every time check_pc_off.tortuobject
# is saved in TortoiseStudio. If you modify this file it will be overwritten. ====
# Quick reference: ANIM_OFF, ANIM_ON, DEFAULT_ANIMATION, COLLIDER_MAIN, SOLID,
# ORIGIN

ANIM_OFF = "off"
ANIM_ON = "on"
DEFAULT_ANIMATION = ANIM_OFF

COLLIDER_MAIN = "main"

SOLID = False
ORIGIN = (16, 31)
# ==== END AUTOGENERATED ====
