# ==== AUTOGENERATED BY TORTUSTUDIO — regenerated every time this scene
# is saved in TortuStudio. If you modify this file it will be overwritten. ====
# Quick reference: OBJ_ROBOT1, OBJ_ROBOT2, OBJ_DIAG_ROBO1, OBJ_DIAG_ROBO2,
# OBJ_RED_SLIME1, LINKS_ROBOT1, LINKS_ROBOT2, LINKS_DIAG_ROBO1,
# LINKS_DIAG_ROBO2

OBJ_ROBOT1 = "robot1"
OBJ_ROBOT2 = "robot2"
OBJ_DIAG_ROBO1 = "diag_robo1"
OBJ_DIAG_ROBO2 = "diag_robo2"
OBJ_RED_SLIME1 = "red_slime1"

LINKS_ROBOT1 = (OBJ_DIAG_ROBO1,)
LINKS_ROBOT2 = (OBJ_DIAG_ROBO2,)
LINKS_DIAG_ROBO1 = (OBJ_ROBOT1,)
LINKS_DIAG_ROBO2 = (OBJ_ROBOT2,)
# ==== END AUTOGENERATED ====
