# ==== AUTOGENERATED BY TORTUSTUDIO — regenerated every time mechaturtle.tortuobject
# is saved in TortuStudio. If you modify this file it will be overwritten. ====
# Quick reference: ANIM_IDLE, ANIM_WALK, ANIM_JUMP, ANIM_FALL, ANIM_ATTACK,
# ANIM_DAMAGE, ANIM_AIR_ATTACK, ANIM_CROUCH, DEFAULT_ANIMATION, COLLIDER_BODY,
# COLLIDER_HEAD, SOLID, ORIGIN

ANIM_IDLE = "idle"
ANIM_WALK = "walk"
ANIM_JUMP = "jump"
ANIM_FALL = "fall"
ANIM_ATTACK = "attack"
ANIM_DAMAGE = "damage"
ANIM_AIR_ATTACK = "air_attack"
ANIM_CROUCH = "crouch"
DEFAULT_ANIMATION = ANIM_IDLE

COLLIDER_BODY = "body"
COLLIDER_HEAD = "head"

SOLID = False
ORIGIN = (18, 31)
# ==== END AUTOGENERATED ====
