# ==== AUTOGENERATED BY TORTUSTUDIO — regenerated every time red_slime.tortuobject
# is saved in TortuStudio. If you modify this file it will be overwritten. ====
# Quick reference: ANIM_IDLE, DEFAULT_ANIMATION, COLLIDER_MAIN, SOLID, ORIGIN

ANIM_IDLE = "idle"
DEFAULT_ANIMATION = ANIM_IDLE

COLLIDER_MAIN = "main"

SOLID = True
ORIGIN = (14, 23)
# ==== END AUTOGENERATED ====
