# ==== AUTOGENERATED BY TORTUSTUDIO — regenerated every time robot.tortuobject
# is saved in TortuStudio. If you modify this file it will be overwritten. ====
# Quick reference: ANIM_IDLE, ANIM_DAMAGE, ANIM_WALK, ANIM_JUMP, ANIM_FALL,
# DEFAULT_ANIMATION, COLLIDER_MAIN, SOLID, ORIGIN, CUSTOMVAR_DIALOGUE,
# CUSTOMVAR_DIALOGUE_DEFAULT

ANIM_IDLE = "idle"
ANIM_DAMAGE = "damage"
ANIM_WALK = "walk"
ANIM_JUMP = "jump"
ANIM_FALL = "fall"
DEFAULT_ANIMATION = ANIM_IDLE

COLLIDER_MAIN = "main"

SOLID = True
ORIGIN = (10, 19)

CUSTOMVAR_DIALOGUE = "dialogue"
CUSTOMVAR_DIALOGUE_DEFAULT = ''
# ==== END AUTOGENERATED ====
