# ==== AUTOGENERATED BY TORTUSTUDIO — regenerated every time this scene
# is saved in TortuStudio. If you modify this file it will be overwritten. ====
# (no placed object instance in this scene has an id yet)

# Assign ids to placed objects in the scene editor to see them here.
# ==== END AUTOGENERATED ====
