# ==== AUTOGENERATED BY TORTUSTUDIO — regenerated every time collider_mechaturtle_attack.tortuobject
# is saved in TortuStudio. If you modify this file it will be overwritten. ====
# Quick reference: ANIM_DEFAULT, DEFAULT_ANIMATION, COLLIDER_MAIN, SOLID,
# ORIGIN

ANIM_DEFAULT = "default"
DEFAULT_ANIMATION = ANIM_DEFAULT

COLLIDER_MAIN = "main"

SOLID = False
ORIGIN = (8, 31)
# ==== END AUTOGENERATED ====
